# Generated by Django 5.0 on 2026-07-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_promotion_magasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categorie', models.CharField(choices=[('mode', 'Mode'), ('beaute', 'Beauté & Santé'), ('restauration', 'Restauration'), ('technologie', 'Technologie'), ('maison', 'Maison'), ('loisirs', 'Loisirs & Culture'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='agences/')),
                ('localisation', models.CharField(help_text='Ex: Niveau 1, Aile Nord', max_length=200)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('est_en_vedette', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
            },
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='magasin',
        ),
        migrations.AddField(
            model_name='promotion',
            name='agence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='app.agence'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Magasin',
        ),
    ]
