# Generated by Django 5.0 on 2026-07-24 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_agence_remove_promotion_magasin_promotion_agence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='localisation',
        ),
        migrations.AddField(
            model_name='agence',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='agence',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='agence',
            name='est_ferme',
            field=models.BooleanField(default=False, verbose_name='fermée ?'),
        ),
        migrations.AddField(
            model_name='agence',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agence',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='agence',
            name='ville',
            field=models.CharField(blank=True, choices=[('Adrar', '01 - Adrar'), ('Chlef', '02 - Chlef'), ('Laghouat', '03 - Laghouat'), ('Oum El Bouaghi', '04 - Oum El Bouaghi'), ('Batna', '05 - Batna'), ('Béjaïa', '06 - Béjaïa'), ('Biskra', '07 - Biskra'), ('Béchar', '08 - Béchar'), ('Blida', '09 - Blida'), ('Bouira', '10 - Bouira'), ('Tamanrasset', '11 - Tamanrasset'), ('Tébessa', '12 - Tébessa'), ('Tlemcen', '13 - Tlemcen'), ('Tiaret', '14 - Tiaret'), ('Tizi Ouzou', '15 - Tizi Ouzou'), ('Alger', '16 - Alger'), ('Djelfa', '17 - Djelfa'), ('Jijel', '18 - Jijel'), ('Sétif', '19 - Sétif'), ('Saïda', '20 - Saïda'), ('Skikda', '21 - Skikda'), ('Sidi Bel Abbès', '22 - Sidi Bel Abbès'), ('Annaba', '23 - Annaba'), ('Guelma', '24 - Guelma'), ('Constantine', '25 - Constantine'), ('Médéa', '26 - Médéa'), ('Mostaganem', '27 - Mostaganem'), ("M'Sila", "28 - M'Sila"), ('Mascara', '29 - Mascara'), ('Ouargla', '30 - Ouargla'), ('Oran', '31 - Oran'), ('El Bayadh', '32 - El Bayadh'), ('Illizi', '33 - Illizi'), ('Bordj Bou Arreridj', '34 - Bordj Bou Arreridj'), ('Boumerdès', '35 - Boumerdès'), ('El Tarf', '36 - El Tarf'), ('Tindouf', '37 - Tindouf'), ('Tissemsilt', '38 - Tissemsilt'), ('El Oued', '39 - El Oued'), ('Khenchela', '40 - Khenchela'), ('Souk Ahras', '41 - Souk Ahras'), ('Tipaza', '42 - Tipaza'), ('Mila', '43 - Mila'), ('Aïn Defla', '44 - Aïn Defla'), ('Naâma', '45 - Naâma'), ('Aïn Témouchent', '46 - Aïn Témouchent'), ('Ghardaïa', '47 - Ghardaïa'), ('Relizane', '48 - Relizane'), ('Timimoun', '49 - Timimoun'), ('Bordj Badji Mokhtar', '50 - Bordj Badji Mokhtar'), ('Ouled Djellal', '51 - Ouled Djellal'), ('Béni Abbès', '52 - Béni Abbès'), ('In Salah', '53 - In Salah'), ('In Guezzam', '54 - In Guezzam'), ('Touggourt', '55 - Touggourt'), ('Djanet', '56 - Djanet'), ("El M'Ghair", "57 - El M'Ghair"), ('El Meniaa', '58 - El Meniaa')], max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='promotions/videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='categorie',
            field=models.CharField(choices=[('base', 'Base'), ('intermediaire', 'Intermediaire'), ('superieur', 'Superieur')], max_length=50),
        ),
        migrations.CreateModel(
            name='AgenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agence/images/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.agence')),
            ],
        ),
        migrations.CreateModel(
            name='AgenceSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('agence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='app.agence')),
            ],
        ),
        migrations.CreateModel(
            name='AgenceValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('period', models.IntegerField(blank=True, choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year')], null=True, verbose_name='Period')),
                ('agence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='app.agence')),
            ],
        ),
        migrations.CreateModel(
            name='AgenceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='agence/videos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='cars/')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('kilometrage', models.PositiveIntegerField(default=0, help_text='Kilométrage en km')),
                ('carburant', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique'), ('lpg', 'GPL')], default='gasoline', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], default='manual', max_length=20)),
                ('etat', models.CharField(choices=[('new', 'Neuf'), ('used', 'Occasion')], default='new', max_length=20)),
                ('ancien_prix', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nouveau_prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_en_vedette', models.BooleanField(default=False)),
                ('est_disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='app.agence')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.car')),
            ],
            options={
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('shop_owner', 'Store Owner'), ('mall_manager', 'Mall Manager'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='Customer', max_length=20)),
                ('phone', models.CharField(blank=True, default='-', max_length=20, null=True)),
                ('city', models.CharField(blank=True, choices=[('Adrar', '01 - Adrar'), ('Chlef', '02 - Chlef'), ('Laghouat', '03 - Laghouat'), ('Oum El Bouaghi', '04 - Oum El Bouaghi'), ('Batna', '05 - Batna'), ('Béjaïa', '06 - Béjaïa'), ('Biskra', '07 - Biskra'), ('Béchar', '08 - Béchar'), ('Blida', '09 - Blida'), ('Bouira', '10 - Bouira'), ('Tamanrasset', '11 - Tamanrasset'), ('Tébessa', '12 - Tébessa'), ('Tlemcen', '13 - Tlemcen'), ('Tiaret', '14 - Tiaret'), ('Tizi Ouzou', '15 - Tizi Ouzou'), ('Alger', '16 - Alger'), ('Djelfa', '17 - Djelfa'), ('Jijel', '18 - Jijel'), ('Sétif', '19 - Sétif'), ('Saïda', '20 - Saïda'), ('Skikda', '21 - Skikda'), ('Sidi Bel Abbès', '22 - Sidi Bel Abbès'), ('Annaba', '23 - Annaba'), ('Guelma', '24 - Guelma'), ('Constantine', '25 - Constantine'), ('Médéa', '26 - Médéa'), ('Mostaganem', '27 - Mostaganem'), ("M'Sila", "28 - M'Sila"), ('Mascara', '29 - Mascara'), ('Ouargla', '30 - Ouargla'), ('Oran', '31 - Oran'), ('El Bayadh', '32 - El Bayadh'), ('Illizi', '33 - Illizi'), ('Bordj Bou Arreridj', '34 - Bordj Bou Arreridj'), ('Boumerdès', '35 - Boumerdès'), ('El Tarf', '36 - El Tarf'), ('Tindouf', '37 - Tindouf'), ('Tissemsilt', '38 - Tissemsilt'), ('El Oued', '39 - El Oued'), ('Khenchela', '40 - Khenchela'), ('Souk Ahras', '41 - Souk Ahras'), ('Tipaza', '42 - Tipaza'), ('Mila', '43 - Mila'), ('Aïn Defla', '44 - Aïn Defla'), ('Naâma', '45 - Naâma'), ('Aïn Témouchent', '46 - Aïn Témouchent'), ('Ghardaïa', '47 - Ghardaïa'), ('Relizane', '48 - Relizane'), ('Timimoun', '49 - Timimoun'), ('Bordj Badji Mokhtar', '50 - Bordj Badji Mokhtar'), ('Ouled Djellal', '51 - Ouled Djellal'), ('Béni Abbès', '52 - Béni Abbès'), ('In Salah', '53 - In Salah'), ('In Guezzam', '54 - In Guezzam'), ('Touggourt', '55 - Touggourt'), ('Djanet', '56 - Djanet'), ("El M'Ghair", "57 - El M'Ghair"), ('El Meniaa', '58 - El Meniaa')], max_length=100, null=True, verbose_name='City')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('image', models.ImageField(default='profiles/default.png', upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], default='FREE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.ManyToManyField(blank=True, related_name='wishlists', to='app.car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.agence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('agence', 'user')},
            },
        ),
    ]
