# Generated by Django 5.0 on 2026-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_agence_localisation_agence_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='adresse',
            field=models.CharField(default='adress', help_text='Ex: Niveau 1, Aile Nord', max_length=200),
            preserve_default=False,
        ),
    ]
