# Generated by Django 5.0 on 2026-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_agence_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencevalidation',
            old_name='start_date',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='agencevalidation',
            old_name='period',
            new_name='periode',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='car',
            name='date_debut_promo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='date_fin_promo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='est_en_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.CharField(blank=True, choices=[('Adrar', '01 - Adrar'), ('Chlef', '02 - Chlef'), ('Laghouat', '03 - Laghouat'), ('Oum El Bouaghi', '04 - Oum El Bouaghi'), ('Batna', '05 - Batna'), ('Béjaïa', '06 - Béjaïa'), ('Biskra', '07 - Biskra'), ('Béchar', '08 - Béchar'), ('Blida', '09 - Blida'), ('Bouira', '10 - Bouira'), ('Tamanrasset', '11 - Tamanrasset'), ('Tébessa', '12 - Tébessa'), ('Tlemcen', '13 - Tlemcen'), ('Tiaret', '14 - Tiaret'), ('Tizi Ouzou', '15 - Tizi Ouzou'), ('Alger', '16 - Alger'), ('Djelfa', '17 - Djelfa'), ('Jijel', '18 - Jijel'), ('Sétif', '19 - Sétif'), ('Saïda', '20 - Saïda'), ('Skikda', '21 - Skikda'), ('Sidi Bel Abbès', '22 - Sidi Bel Abbès'), ('Annaba', '23 - Annaba'), ('Guelma', '24 - Guelma'), ('Constantine', '25 - Constantine'), ('Médéa', '26 - Médéa'), ('Mostaganem', '27 - Mostaganem'), ("M'Sila", "28 - M'Sila"), ('Mascara', '29 - Mascara'), ('Ouargla', '30 - Ouargla'), ('Oran', '31 - Oran'), ('El Bayadh', '32 - El Bayadh'), ('Illizi', '33 - Illizi'), ('Bordj Bou Arreridj', '34 - Bordj Bou Arreridj'), ('Boumerdès', '35 - Boumerdès'), ('El Tarf', '36 - El Tarf'), ('Tindouf', '37 - Tindouf'), ('Tissemsilt', '38 - Tissemsilt'), ('El Oued', '39 - El Oued'), ('Khenchela', '40 - Khenchela'), ('Souk Ahras', '41 - Souk Ahras'), ('Tipaza', '42 - Tipaza'), ('Mila', '43 - Mila'), ('Aïn Defla', '44 - Aïn Defla'), ('Naâma', '45 - Naâma'), ('Aïn Témouchent', '46 - Aïn Témouchent'), ('Ghardaïa', '47 - Ghardaïa'), ('Relizane', '48 - Relizane'), ('Timimoun', '49 - Timimoun'), ('Bordj Badji Mokhtar', '50 - Bordj Badji Mokhtar'), ('Ouled Djellal', '51 - Ouled Djellal'), ('Béni Abbès', '52 - Béni Abbès'), ('In Salah', '53 - In Salah'), ('In Guezzam', '54 - In Guezzam'), ('Touggourt', '55 - Touggourt'), ('Djanet', '56 - Djanet'), ("El M'Ghair", "57 - El M'Ghair"), ('El Meniaa', '58 - El Meniaa')], max_length=100, null=True, verbose_name='Wilaya'),
        ),
        migrations.AlterField(
            model_name='car',
            name='etat',
            field=models.CharField(choices=[('neuf', 'Neuf'), ('moins_de_3ans', 'Moins de 3 ans'), ('occasion', 'Occasion')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agence_owner', 'Agence Owner'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='Customer', max_length=20),
        ),
    ]
