# Generated by Django 5.0 on 2026-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_start_date_agencevalidation_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='date_ouverture',
            field=models.DateField(blank=True, null=True, verbose_name="date d'ouverture (si future)"),
        ),
        migrations.AddField(
            model_name='agence',
            name='heure_fermeture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agence',
            name='heure_ouverture',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
