# Generated by Django 5.0 on 2026-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_agence_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarImage',
            new_name='CarImages',
        ),
        migrations.RemoveField(
            model_name='car',
            name='carburant',
        ),
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='car',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='boite_de_vitesse',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique'), ('semi_automatique', 'Semi-automatique')], default='Automatique', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='couleur',
            field=models.CharField(blank=True, default='Black', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='energie',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('gpl', 'GPL'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], default='Essence', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='finition',
            field=models.CharField(blank=True, default='Full options', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='moteur',
            field=models.CharField(blank=True, default='1.5 181ch 16v turbo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='etat',
            field=models.CharField(choices=[('neuf', 'Neuf'), ('moins_de_3ans', 'Moins de 3 ans'), ('occasion', 'Occasion')], default='neuf', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='marque',
            field=models.CharField(choices=[('Dacia', 'Dacia'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Renault', 'Renault'), ('Peugeot', 'Peugeot'), ('Citroën', 'Citroën'), ('Fiat', 'Fiat'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Ford', 'Ford'), ('Opel', 'Opel'), ('Nissan', 'Nissan'), ('Suzuki', 'Suzuki'), ('Volkswagen', 'Volkswagen'), ('Chevrolet', 'Chevrolet'), ('Lexus', 'Lexus'), ('Volvo', 'Volvo'), ('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('McLaren', 'McLaren'), ('Aston Martin', 'Aston Martin'), ('Bentley', 'Bentley'), ('Rolls-Royce', 'Rolls-Royce'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Maserati', 'Maserati'), ('Mini', 'Mini'), ('Smart', 'Smart'), ('Lada', 'Lada'), ('Fiat', 'Fiat'), ('Chery', 'Chery'), ('Haval', 'Haval'), ('Geely', 'Geely'), ('MG', 'MG'), ('Other', 'Other')], default='', max_length=20),
        ),
    ]
