# Generated by Django 5.0 on 2026-07-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_carimage_carimages_remove_car_carburant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimages',
            old_name='legende',
            new_name='caption',
        ),
    ]
