# Generated by Django 5.0 on 2026-07-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_legende_carimages_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='categorie',
        ),
    ]
