# Generated by Django 5.0 on 2026-07-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_agence_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AlterField(
            model_name='car',
            name='boite_de_vitesse',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique'), ('semi_automatique', 'Semi-automatique')], default='automatique', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='energie',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('gpl', 'GPL'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], default='essence', max_length=20),
        ),
    ]
