# Generated by Django 5.0 on 2026-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_car_image_alter_car_boite_de_vitesse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='google_map',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Google Map URL'),
        ),
    ]
