# Generated by Django 5.0 on 2026-07-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_agence_google_map'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgenceImage',
            new_name='AgenceImages',
        ),
        migrations.RenameModel(
            old_name='AgenceVideo',
            new_name='AgenceVideos',
        ),
    ]
