# Generated by Django 5.0 on 2026-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_agenceimage_agenceimages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-creer_le'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.RenameField(
            model_name='agencereview',
            old_name='created_at',
            new_name='creer_le',
        ),
        migrations.RenameField(
            model_name='agencereview',
            old_name='rating',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='created_at',
            new_name='creer_le',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='updated_at',
            new_name='modifier_le',
        ),
        migrations.RenameField(
            model_name='carimages',
            old_name='created_at',
            new_name='creer_le',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='creer_le',
        ),
        migrations.RemoveField(
            model_name='agencereview',
            name='comment',
        ),
        migrations.AddField(
            model_name='agencereview',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
    ]
