# Generated by Django 5.0 on 2026-07-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.RenameField(
            model_name='agencereview',
            old_name='creer_le',
            new_name='cree_le',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='creer_le',
            new_name='cree_le',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='modifier_le',
            new_name='modifie_le',
        ),
        migrations.RenameField(
            model_name='carimages',
            old_name='creer_le',
            new_name='cree_le',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='creer_le',
            new_name='cree_le',
        ),
    ]
