# Generated by Django 5.0 on 2026-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenceimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencevideos',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
