# Generated by Django 5.0 on 2026-07-31 17:23

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify
import uuid

def populate_car_slugs(apps, schema_editor):
    Car = apps.get_model('app', 'Car')
    for car in Car.objects.all():
        base_slug = slugify(f"{car.marque} {car.modele}")
        if not base_slug:
            base_slug = "car"
        slug = base_slug
        while Car.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{uuid.uuid4().hex[:5]}"
        car.slug = slug
        car.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_agenceimages_is_main_agencevideos_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to='agences/banners/'),
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='app.agence'),
        ),
        migrations.RunPython(populate_car_slugs),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
