# Generated by Django 5.0 on 2026-08-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_agence_banniere_car_slug_car_views_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='banniere',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='image',
        ),
    ]
