# Generated by Django 5.0 on 2026-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_agence_banniere_remove_agence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cars/videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ancien_prix',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='nouveau_prix',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
    ]
