# Generated by Django 5.0 on 2026-08-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_car_video_alter_car_ancien_prix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimages',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='carimages',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='carimages',
            name='order',
        ),
    ]
