# Generated by Django 5.0 on 2026-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_carimages_options_remove_carimages_is_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimages',
            options={'ordering': ['order', 'cree_le'], 'verbose_name_plural': 'Images des voitures'},
        ),
        migrations.AddField(
            model_name='carimages',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
