# Generated by Django 5.0 on 2026-08-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_carimages_options_carimages_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimages',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Images des voitures'},
        ),
    ]
