# Generated by Django 5.0 on 2026-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_carimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Voiture', 'verbose_name_plural': 'Voitures'},
        ),
        migrations.AlterModelOptions(
            name='carimages',
            options={'ordering': ['order', 'cree_le'], 'verbose_name_plural': 'Images des voitures'},
        ),
        migrations.AddField(
            model_name='car',
            name='description_promo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='titre_promo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
