# Generated by Django 5.0 on 2026-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_car_options_alter_carimages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='date',
        ),
        migrations.AddField(
            model_name='evenement',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
