# Generated by Django 5.0 on 2026-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_evenement_date_evenement_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='boite_de_vitesse',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique'), ('semi_automatique', 'Semi-automatique')], default='manuelle', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='couleur',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
