# Generated by Django 5.0 on 2026-08-09 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_car_boite_de_vitesse_alter_car_couleur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleblog',
            old_name='date_publication',
            new_name='cree_le',
        ),
        migrations.AddField(
            model_name='articleblog',
            name='date_debut_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleblog',
            name='date_fin_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
