# Generated by Django 5.0 on 2026-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_date_publication_articleblog_cree_le_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='lu_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('Faible', 'Low'), ('Normale', 'Normal'), ('Élevée', 'High')], db_index=True, default='Normale', max_length=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='repondu_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('Nouveau', 'New'), ('Lu', 'Read'), ('Répondu', 'Replied'), ('Archivé', 'Archived')], db_index=True, default='Nouveau', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='date_debut_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='date_fin_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
