# Generated by Django 5.0 on 2026-08-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_contactmessage_options_contactmessage_lu_le_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblog',
            name='date_debut_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='date_fin_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
