# Generated by Django 5.0 on 2026-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_articleblog_date_debut_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Name of brand')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifié_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-date_debut'],
            },
        ),
    ]
