# Generated by Django 5.0 on 2026-08-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='nome',
            new_name='nom',
        ),
    ]
