# Generated by Django 5.0 on 2026-08-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_nome_brand_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adresse',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('proprietaire_agence', "Proprietaire d'Agence"), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='Customer', max_length=20),
        ),
    ]
