# Generated by Django 5.0 on 2026-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_profile_adresse_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='afficher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='afficher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='afficher',
            field=models.BooleanField(default=False),
        ),
    ]
