# Generated by Django 5.0 on 2026-08-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_articleblog_afficher_brand_afficher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='nouveau_prix',
            new_name='prix_actuel',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='ancien_prix',
            new_name='prix_ancien',
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
