# Generated by Django 5.0 on 2026-08-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_nouveau_prix_car_prix_actuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
