# Generated by Django 5.0 on 2026-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
