# Generated by Django 5.0 on 2026-08-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_agence_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='etat',
            new_name='statut',
        ),
    ]
