# Generated by Django 5.0 on 2026-09-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_etat_car_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_publication_promo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
