# Generated by Django 5.0 on 2026-09-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_car_date_publication_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='date_publication_promo',
            new_name='date_debut_publication_promo',
        ),
    ]
