# Generated by Django 5.0 on 2026-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_date_publication_promo_car_date_debut_publication_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agence',
            old_name='adresse',
            new_name='emplacement',
        ),
        migrations.RemoveField(
            model_name='agenceimages',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='agencevideos',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='agence',
            name='date_debut_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agence',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agence',
            name='nombre_jours_validite',
            field=models.IntegerField(default=30),
        ),
    ]
