# Generated by Django 5.0 on 2026-09-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_adresse_agence_emplacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenceimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
