# Generated by Django 5.0 on 2026-09-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_agenceimages_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencevideos',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
