# Generated by Django 5.0 on 2026-09-06 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_agencevideos_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencevideos',
            options={'ordering': ['-is_main', '-cree_le']},
        ),
        migrations.RenameField(
            model_name='agencevideos',
            old_name='legende',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='agencevideos',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
