# Generated by Django 5.0 on 2026-09-06 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_agencevideos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenceimages',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
