# Generated by Django 5.0 on 2026-09-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_agenceimages_cree_le'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenceimages',
            old_name='legende',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='car',
            name='video_titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
