# Generated by Django 5.0 on 2026-09-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_rename_legende_agenceimages_titre_car_video_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenceimages',
            old_name='titre',
            new_name='legende',
        ),
        migrations.RenameField(
            model_name='agencevideos',
            old_name='titre',
            new_name='legende',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='video_titre',
            new_name='video_legende',
        ),
        migrations.RenameField(
            model_name='carimages',
            old_name='caption',
            new_name='legende',
        ),
    ]
