# Generated by Django 5.0 on 2026-09-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_rename_titre_agenceimages_legende_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenceimages',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
