# Generated by Django 5.0 on 2026-09-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_agenceimages_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
