# Generated by Django 5.0 on 2026-09-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_carimages_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimages',
            options={'ordering': ['-is_main', '-cree_le'], 'verbose_name_plural': 'Images des voitures'},
        ),
    ]
