# Generated by Django 5.0 on 2026-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_carimages_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agence',
            old_name='date_debut_validite',
            new_name='date_debut_abonnement',
        ),
        migrations.RenameField(
            model_name='agence',
            old_name='est_valide',
            new_name='est_bloquee',
        ),
        migrations.RenameField(
            model_name='agence',
            old_name='nombre_jours_validite',
            new_name='nombre_jours_abonnement',
        ),
        migrations.AddField(
            model_name='agence',
            name='cause_blocage',
            field=models.CharField(blank=True, help_text='Ex: Non respect des règles', max_length=200, null=True),
        ),
    ]
